// Home airports people can start from. Name and position only: that is all the flight estimate needs.
export type Airport = { iata: string; name: string; country: string; lat: number; lon: number; hub?: boolean };

export const AIRPORTS: Airport[] = [
  { iata: "IST", name: "Istanbul (Istanbul Airport)", country: "Türkiye", lat: 41.26, lon: 28.74, hub: true },
  { iata: "SAW", name: "Istanbul (Sabiha Gökçen)", country: "Türkiye", lat: 40.9, lon: 29.31 },
  { iata: "ADB", name: "Izmir", country: "Türkiye", lat: 38.29, lon: 27.16 },
  { iata: "AYT", name: "Antalya", country: "Türkiye", lat: 36.9, lon: 30.8 },
  { iata: "ESB", name: "Ankara", country: "Türkiye", lat: 40.13, lon: 32.99 },
  { iata: "BJV", name: "Bodrum", country: "Türkiye", lat: 37.25, lon: 27.67 },
  { iata: "DLM", name: "Dalaman (Muğla, Fethiye)", country: "Türkiye", lat: 36.71, lon: 28.79 },
  { iata: "TZX", name: "Trabzon", country: "Türkiye", lat: 40.99, lon: 39.79 },
  { iata: "GZT", name: "Gaziantep", country: "Türkiye", lat: 36.95, lon: 37.48 },
  { iata: "ASR", name: "Kayseri", country: "Türkiye", lat: 38.77, lon: 35.49 },
  { iata: "NAV", name: "Nevşehir (Cappadocia)", country: "Türkiye", lat: 38.77, lon: 34.53 },
  { iata: "ADA", name: "Adana", country: "Türkiye", lat: 36.98, lon: 35.28 },
  { iata: "VAN", name: "Van", country: "Türkiye", lat: 38.46, lon: 43.33 },
  { iata: "DIY", name: "Diyarbakır", country: "Türkiye", lat: 37.89, lon: 40.2 },
  { iata: "SZF", name: "Samsun", country: "Türkiye", lat: 41.25, lon: 36.57 },
  { iata: "KYA", name: "Konya", country: "Türkiye", lat: 37.98, lon: 32.56 },
  { iata: "YEI", name: "Bursa (Yenişehir)", country: "Türkiye", lat: 40.26, lon: 29.56 },
  { iata: "DNZ", name: "Denizli", country: "Türkiye", lat: 37.79, lon: 29.7 },
  { iata: "HTY", name: "Hatay", country: "Türkiye", lat: 36.36, lon: 36.28 },
  { iata: "ERZ", name: "Erzurum", country: "Türkiye", lat: 39.96, lon: 41.17 },
  { iata: "MLX", name: "Malatya", country: "Türkiye", lat: 38.44, lon: 38.09 },
  { iata: "CKZ", name: "Çanakkale", country: "Türkiye", lat: 40.14, lon: 26.43 },
  { iata: "LHR", name: "London Heathrow", country: "United Kingdom", lat: 51.47, lon: -0.45, hub: true },
  { iata: "LGW", name: "London Gatwick", country: "United Kingdom", lat: 51.15, lon: -0.18 },
  { iata: "STN", name: "London Stansted", country: "United Kingdom", lat: 51.89, lon: 0.26 },
  { iata: "MAN", name: "Manchester", country: "United Kingdom", lat: 53.35, lon: -2.27 },
  { iata: "EDI", name: "Edinburgh", country: "United Kingdom", lat: 55.95, lon: -3.37 },
  { iata: "GLA", name: "Glasgow", country: "United Kingdom", lat: 55.87, lon: -4.43 },
  { iata: "BHX", name: "Birmingham", country: "United Kingdom", lat: 52.45, lon: -1.75 },
  { iata: "BRS", name: "Bristol", country: "United Kingdom", lat: 51.38, lon: -2.72 },
  { iata: "DUB", name: "Dublin", country: "Ireland", lat: 53.43, lon: -6.27, hub: true },
  { iata: "ORK", name: "Cork", country: "Ireland", lat: 51.84, lon: -8.49 },
  { iata: "CDG", name: "Paris Charles de Gaulle", country: "France", lat: 49.01, lon: 2.55, hub: true },
  { iata: "ORY", name: "Paris Orly", country: "France", lat: 48.72, lon: 2.38 },
  { iata: "NCE", name: "Nice", country: "France", lat: 43.66, lon: 7.22 },
  { iata: "LYS", name: "Lyon", country: "France", lat: 45.73, lon: 5.09 },
  { iata: "MRS", name: "Marseille", country: "France", lat: 43.44, lon: 5.22 },
  { iata: "TLS", name: "Toulouse", country: "France", lat: 43.63, lon: 1.36 },
  { iata: "BOD", name: "Bordeaux", country: "France", lat: 44.83, lon: -0.72 },
  { iata: "AMS", name: "Amsterdam", country: "Netherlands", lat: 52.31, lon: 4.76, hub: true },
  { iata: "BRU", name: "Brussels", country: "Belgium", lat: 50.9, lon: 4.48 },
  { iata: "FRA", name: "Frankfurt", country: "Germany", lat: 50.04, lon: 8.57, hub: true },
  { iata: "MUC", name: "Munich", country: "Germany", lat: 48.35, lon: 11.79, hub: true },
  { iata: "BER", name: "Berlin", country: "Germany", lat: 52.36, lon: 13.5 },
  { iata: "HAM", name: "Hamburg", country: "Germany", lat: 53.63, lon: 9.99 },
  { iata: "DUS", name: "Düsseldorf", country: "Germany", lat: 51.29, lon: 6.77 },
  { iata: "CGN", name: "Cologne", country: "Germany", lat: 50.87, lon: 7.14 },
  { iata: "STR", name: "Stuttgart", country: "Germany", lat: 48.69, lon: 9.22 },
  { iata: "ZRH", name: "Zurich", country: "Switzerland", lat: 47.46, lon: 8.55, hub: true },
  { iata: "GVA", name: "Geneva", country: "Switzerland", lat: 46.24, lon: 6.11 },
  { iata: "BSL", name: "Basel", country: "Switzerland", lat: 47.59, lon: 7.53 },
  { iata: "VIE", name: "Vienna", country: "Austria", lat: 48.11, lon: 16.57, hub: true },
  { iata: "MAD", name: "Madrid", country: "Spain", lat: 40.49, lon: -3.57, hub: true },
  { iata: "BCN", name: "Barcelona", country: "Spain", lat: 41.3, lon: 2.08, hub: true },
  { iata: "AGP", name: "Málaga", country: "Spain", lat: 36.67, lon: -4.5 },
  { iata: "VLC", name: "Valencia", country: "Spain", lat: 39.49, lon: -0.48 },
  { iata: "SVQ", name: "Seville", country: "Spain", lat: 37.42, lon: -5.9 },
  { iata: "PMI", name: "Palma de Mallorca", country: "Spain", lat: 39.55, lon: 2.74 },
  { iata: "TFS", name: "Tenerife South", country: "Spain", lat: 28.04, lon: -16.57 },
  { iata: "LPA", name: "Gran Canaria", country: "Spain", lat: 27.93, lon: -15.39 },
  { iata: "BIO", name: "Bilbao", country: "Spain", lat: 43.3, lon: -2.91 },
  { iata: "LIS", name: "Lisbon", country: "Portugal", lat: 38.77, lon: -9.13 },
  { iata: "OPO", name: "Porto", country: "Portugal", lat: 41.24, lon: -8.68 },
  { iata: "FAO", name: "Faro", country: "Portugal", lat: 37.01, lon: -7.97 },
  { iata: "FNC", name: "Madeira (Funchal)", country: "Portugal", lat: 32.69, lon: -16.77 },
  { iata: "FCO", name: "Rome", country: "Italy", lat: 41.8, lon: 12.25, hub: true },
  { iata: "MXP", name: "Milan Malpensa", country: "Italy", lat: 45.63, lon: 8.72 },
  { iata: "VCE", name: "Venice", country: "Italy", lat: 45.5, lon: 12.35 },
  { iata: "NAP", name: "Naples", country: "Italy", lat: 40.89, lon: 14.29 },
  { iata: "BLQ", name: "Bologna", country: "Italy", lat: 44.53, lon: 11.29 },
  { iata: "FLR", name: "Florence", country: "Italy", lat: 43.81, lon: 11.2 },
  { iata: "PMO", name: "Palermo", country: "Italy", lat: 38.18, lon: 13.1 },
  { iata: "CTA", name: "Catania", country: "Italy", lat: 37.47, lon: 15.07 },
  { iata: "TRN", name: "Turin", country: "Italy", lat: 45.2, lon: 7.65 },
  { iata: "ATH", name: "Athens", country: "Greece", lat: 37.94, lon: 23.94 },
  { iata: "SKG", name: "Thessaloniki", country: "Greece", lat: 40.52, lon: 22.97 },
  { iata: "HER", name: "Heraklion (Crete)", country: "Greece", lat: 35.34, lon: 25.18 },
  { iata: "JTR", name: "Santorini", country: "Greece", lat: 36.4, lon: 25.48 },
  { iata: "CPH", name: "Copenhagen", country: "Denmark", lat: 55.62, lon: 12.65 },
  { iata: "ARN", name: "Stockholm", country: "Sweden", lat: 59.65, lon: 17.92 },
  { iata: "OSL", name: "Oslo", country: "Norway", lat: 60.19, lon: 11.1 },
  { iata: "HEL", name: "Helsinki", country: "Finland", lat: 60.32, lon: 24.96 },
  { iata: "KEF", name: "Reykjavik", country: "Iceland", lat: 63.99, lon: -22.62 },
  { iata: "WAW", name: "Warsaw", country: "Poland", lat: 52.17, lon: 20.97 },
  { iata: "KRK", name: "Kraków", country: "Poland", lat: 50.08, lon: 19.78 },
  { iata: "PRG", name: "Prague", country: "Czechia", lat: 50.1, lon: 14.26 },
  { iata: "BUD", name: "Budapest", country: "Hungary", lat: 47.44, lon: 19.26 },
  { iata: "OTP", name: "Bucharest", country: "Romania", lat: 44.57, lon: 26.08 },
  { iata: "SOF", name: "Sofia", country: "Bulgaria", lat: 42.7, lon: 23.41 },
  { iata: "BEG", name: "Belgrade", country: "Serbia", lat: 44.82, lon: 20.31 },
  { iata: "ZAG", name: "Zagreb", country: "Croatia", lat: 45.74, lon: 16.07 },
  { iata: "SPU", name: "Split", country: "Croatia", lat: 43.54, lon: 16.3 },
  { iata: "DBV", name: "Dubrovnik", country: "Croatia", lat: 42.56, lon: 18.27 },
  { iata: "LJU", name: "Ljubljana", country: "Slovenia", lat: 46.22, lon: 14.46 },
  { iata: "SJJ", name: "Sarajevo", country: "Bosnia and Herzegovina", lat: 43.82, lon: 18.33 },
  { iata: "TIA", name: "Tirana", country: "Albania", lat: 41.41, lon: 19.72 },
  { iata: "SKP", name: "Skopje", country: "North Macedonia", lat: 41.96, lon: 21.62 },
  { iata: "RIX", name: "Riga", country: "Latvia", lat: 56.92, lon: 23.97 },
  { iata: "VNO", name: "Vilnius", country: "Lithuania", lat: 54.63, lon: 25.28 },
  { iata: "TLL", name: "Tallinn", country: "Estonia", lat: 59.41, lon: 24.83 },
  { iata: "LCA", name: "Larnaca", country: "Cyprus", lat: 34.88, lon: 33.62 },
  { iata: "MLA", name: "Malta", country: "Malta", lat: 35.86, lon: 14.48 },
  { iata: "TBS", name: "Tbilisi", country: "Georgia", lat: 41.67, lon: 44.95 },
  { iata: "EVN", name: "Yerevan", country: "Armenia", lat: 40.15, lon: 44.4 },
  { iata: "GYD", name: "Baku", country: "Azerbaijan", lat: 40.47, lon: 50.05 },
  { iata: "DXB", name: "Dubai", country: "UAE", lat: 25.25, lon: 55.36, hub: true },
  { iata: "AUH", name: "Abu Dhabi", country: "UAE", lat: 24.43, lon: 54.65 },
  { iata: "SHJ", name: "Sharjah", country: "UAE", lat: 25.33, lon: 55.52 },
  { iata: "DOH", name: "Doha", country: "Qatar", lat: 25.27, lon: 51.61, hub: true },
  { iata: "BAH", name: "Bahrain", country: "Bahrain", lat: 26.27, lon: 50.63 },
  { iata: "KWI", name: "Kuwait City", country: "Kuwait", lat: 29.23, lon: 47.97 },
  { iata: "RUH", name: "Riyadh", country: "Saudi Arabia", lat: 24.96, lon: 46.7 },
  { iata: "JED", name: "Jeddah", country: "Saudi Arabia", lat: 21.68, lon: 39.16 },
  { iata: "DMM", name: "Dammam", country: "Saudi Arabia", lat: 26.47, lon: 49.8 },
  { iata: "MCT", name: "Muscat", country: "Oman", lat: 23.59, lon: 58.28 },
  { iata: "AMM", name: "Amman", country: "Jordan", lat: 31.72, lon: 35.99 },
  { iata: "BEY", name: "Beirut", country: "Lebanon", lat: 33.82, lon: 35.49 },
  { iata: "TLV", name: "Tel Aviv", country: "Israel", lat: 32.01, lon: 34.89 },
  { iata: "CAI", name: "Cairo", country: "Egypt", lat: 30.12, lon: 31.41 },
  { iata: "HRG", name: "Hurghada", country: "Egypt", lat: 27.18, lon: 33.8 },
  { iata: "CMN", name: "Casablanca", country: "Morocco", lat: 33.37, lon: -7.59 },
  { iata: "RAK", name: "Marrakech", country: "Morocco", lat: 31.61, lon: -8.04 },
  { iata: "TUN", name: "Tunis", country: "Tunisia", lat: 36.85, lon: 10.23 },
  { iata: "ALG", name: "Algiers", country: "Algeria", lat: 36.69, lon: 3.22 },
  { iata: "JNB", name: "Johannesburg", country: "South Africa", lat: -26.14, lon: 28.25 },
  { iata: "CPT", name: "Cape Town", country: "South Africa", lat: -33.97, lon: 18.6 },
  { iata: "DUR", name: "Durban", country: "South Africa", lat: -29.61, lon: 31.12 },
  { iata: "NBO", name: "Nairobi", country: "Kenya", lat: -1.32, lon: 36.93 },
  { iata: "ADD", name: "Addis Ababa", country: "Ethiopia", lat: 8.98, lon: 38.8 },
  { iata: "LOS", name: "Lagos", country: "Nigeria", lat: 6.58, lon: 3.32 },
  { iata: "ACC", name: "Accra", country: "Ghana", lat: 5.61, lon: -0.17 },
  { iata: "DSS", name: "Dakar", country: "Senegal", lat: 14.67, lon: -17.07 },
  { iata: "DAR", name: "Dar es Salaam", country: "Tanzania", lat: -6.88, lon: 39.2 },
  { iata: "ZNZ", name: "Zanzibar", country: "Tanzania", lat: -6.22, lon: 39.22 },
  { iata: "MRU", name: "Mauritius", country: "Mauritius", lat: -20.43, lon: 57.68 },
  { iata: "EBB", name: "Entebbe (Kampala)", country: "Uganda", lat: 0.04, lon: 32.44 },
  { iata: "KGL", name: "Kigali", country: "Rwanda", lat: -1.97, lon: 30.14 },
  { iata: "WDH", name: "Windhoek", country: "Namibia", lat: -22.48, lon: 17.47 },
  { iata: "LUN", name: "Lusaka", country: "Zambia", lat: -15.33, lon: 28.45 },
  { iata: "HRE", name: "Harare", country: "Zimbabwe", lat: -17.93, lon: 31.09 },
  { iata: "SIN", name: "Singapore", country: "Singapore", lat: 1.36, lon: 103.99, hub: true },
  { iata: "BKK", name: "Bangkok", country: "Thailand", lat: 13.69, lon: 100.75, hub: true },
  { iata: "HKT", name: "Phuket", country: "Thailand", lat: 8.11, lon: 98.32 },
  { iata: "CNX", name: "Chiang Mai", country: "Thailand", lat: 18.77, lon: 98.96 },
  { iata: "KUL", name: "Kuala Lumpur", country: "Malaysia", lat: 2.75, lon: 101.71, hub: true },
  { iata: "CGK", name: "Jakarta", country: "Indonesia", lat: -6.13, lon: 106.66 },
  { iata: "DPS", name: "Bali (Denpasar)", country: "Indonesia", lat: -8.75, lon: 115.17 },
  { iata: "MNL", name: "Manila", country: "Philippines", lat: 14.51, lon: 121.02 },
  { iata: "SGN", name: "Ho Chi Minh City", country: "Vietnam", lat: 10.82, lon: 106.65 },
  { iata: "HAN", name: "Hanoi", country: "Vietnam", lat: 21.22, lon: 105.81 },
  { iata: "PNH", name: "Phnom Penh", country: "Cambodia", lat: 11.55, lon: 104.84 },
  { iata: "RGN", name: "Yangon", country: "Myanmar", lat: 16.91, lon: 96.13 },
  { iata: "DAC", name: "Dhaka", country: "Bangladesh", lat: 23.84, lon: 90.4 },
  { iata: "DEL", name: "Delhi", country: "India", lat: 28.56, lon: 77.1, hub: true },
  { iata: "BOM", name: "Mumbai", country: "India", lat: 19.09, lon: 72.87 },
  { iata: "BLR", name: "Bengaluru", country: "India", lat: 13.2, lon: 77.71 },
  { iata: "MAA", name: "Chennai", country: "India", lat: 12.99, lon: 80.17 },
  { iata: "HYD", name: "Hyderabad", country: "India", lat: 17.24, lon: 78.43 },
  { iata: "CCU", name: "Kolkata", country: "India", lat: 22.65, lon: 88.45 },
  { iata: "COK", name: "Kochi", country: "India", lat: 10.15, lon: 76.4 },
  { iata: "AMD", name: "Ahmedabad", country: "India", lat: 23.07, lon: 72.63 },
  { iata: "KTM", name: "Kathmandu", country: "Nepal", lat: 27.7, lon: 85.36 },
  { iata: "CMB", name: "Colombo", country: "Sri Lanka", lat: 7.18, lon: 79.88 },
  { iata: "MLE", name: "Malé (Maldives)", country: "Maldives", lat: 4.19, lon: 73.53 },
  { iata: "KHI", name: "Karachi", country: "Pakistan", lat: 24.91, lon: 67.16 },
  { iata: "LHE", name: "Lahore", country: "Pakistan", lat: 31.52, lon: 74.4 },
  { iata: "ISB", name: "Islamabad", country: "Pakistan", lat: 33.55, lon: 72.83 },
  { iata: "TAS", name: "Tashkent", country: "Uzbekistan", lat: 41.26, lon: 69.28 },
  { iata: "ALA", name: "Almaty", country: "Kazakhstan", lat: 43.35, lon: 77.04 },
  { iata: "NRT", name: "Tokyo Narita", country: "Japan", lat: 35.77, lon: 140.39 },
  { iata: "HND", name: "Tokyo Haneda", country: "Japan", lat: 35.55, lon: 139.78, hub: true },
  { iata: "KIX", name: "Osaka (Kansai)", country: "Japan", lat: 34.43, lon: 135.24 },
  { iata: "NGO", name: "Nagoya", country: "Japan", lat: 34.86, lon: 136.81 },
  { iata: "FUK", name: "Fukuoka", country: "Japan", lat: 33.59, lon: 130.45 },
  { iata: "CTS", name: "Sapporo", country: "Japan", lat: 42.78, lon: 141.69 },
  { iata: "ICN", name: "Seoul Incheon", country: "South Korea", lat: 37.46, lon: 126.44, hub: true },
  { iata: "PUS", name: "Busan", country: "South Korea", lat: 35.18, lon: 128.94 },
  { iata: "TPE", name: "Taipei", country: "Taiwan", lat: 25.08, lon: 121.23 },
  { iata: "HKG", name: "Hong Kong", country: "Hong Kong", lat: 22.31, lon: 113.91, hub: true },
  { iata: "PEK", name: "Beijing", country: "China", lat: 40.08, lon: 116.58, hub: true },
  { iata: "PVG", name: "Shanghai Pudong", country: "China", lat: 31.14, lon: 121.81, hub: true },
  { iata: "CAN", name: "Guangzhou", country: "China", lat: 23.39, lon: 113.3 },
  { iata: "SZX", name: "Shenzhen", country: "China", lat: 22.64, lon: 113.81 },
  { iata: "CTU", name: "Chengdu", country: "China", lat: 30.58, lon: 103.95 },
  { iata: "ULN", name: "Ulaanbaatar", country: "Mongolia", lat: 47.84, lon: 106.77 },
  { iata: "JFK", name: "New York JFK", country: "USA", lat: 40.64, lon: -73.78, hub: true },
  { iata: "EWR", name: "New York Newark", country: "USA", lat: 40.69, lon: -74.17 },
  { iata: "BOS", name: "Boston", country: "USA", lat: 42.36, lon: -71.01 },
  { iata: "PHL", name: "Philadelphia", country: "USA", lat: 39.87, lon: -75.24 },
  { iata: "IAD", name: "Washington Dulles", country: "USA", lat: 38.95, lon: -77.46 },
  { iata: "DCA", name: "Washington Reagan", country: "USA", lat: 38.85, lon: -77.04 },
  { iata: "BWI", name: "Baltimore", country: "USA", lat: 39.18, lon: -76.67 },
  { iata: "ATL", name: "Atlanta", country: "USA", lat: 33.64, lon: -84.43, hub: true },
  { iata: "MIA", name: "Miami", country: "USA", lat: 25.8, lon: -80.29 },
  { iata: "MCO", name: "Orlando", country: "USA", lat: 28.43, lon: -81.31 },
  { iata: "TPA", name: "Tampa", country: "USA", lat: 27.98, lon: -82.53 },
  { iata: "FLL", name: "Fort Lauderdale", country: "USA", lat: 26.07, lon: -80.15 },
  { iata: "CLT", name: "Charlotte", country: "USA", lat: 35.21, lon: -80.94 },
  { iata: "RDU", name: "Raleigh-Durham", country: "USA", lat: 35.88, lon: -78.79 },
  { iata: "BNA", name: "Nashville", country: "USA", lat: 36.12, lon: -86.68 },
  { iata: "MSY", name: "New Orleans", country: "USA", lat: 29.99, lon: -90.26 },
  { iata: "IAH", name: "Houston", country: "USA", lat: 29.98, lon: -95.34 },
  { iata: "DFW", name: "Dallas-Fort Worth", country: "USA", lat: 32.9, lon: -97.04, hub: true },
  { iata: "AUS", name: "Austin", country: "USA", lat: 30.2, lon: -97.67 },
  { iata: "SAT", name: "San Antonio", country: "USA", lat: 29.53, lon: -98.47 },
  { iata: "DEN", name: "Denver", country: "USA", lat: 39.86, lon: -104.67 },
  { iata: "PHX", name: "Phoenix", country: "USA", lat: 33.43, lon: -112.01 },
  { iata: "LAS", name: "Las Vegas", country: "USA", lat: 36.08, lon: -115.15 },
  { iata: "SLC", name: "Salt Lake City", country: "USA", lat: 40.79, lon: -111.98 },
  { iata: "LAX", name: "Los Angeles", country: "USA", lat: 33.94, lon: -118.41, hub: true },
  { iata: "SAN", name: "San Diego", country: "USA", lat: 32.73, lon: -117.19 },
  { iata: "SFO", name: "San Francisco", country: "USA", lat: 37.62, lon: -122.38, hub: true },
  { iata: "SJC", name: "San Jose (CA)", country: "USA", lat: 37.36, lon: -121.93 },
  { iata: "SEA", name: "Seattle", country: "USA", lat: 47.45, lon: -122.31 },
  { iata: "PDX", name: "Portland (OR)", country: "USA", lat: 45.59, lon: -122.6 },
  { iata: "ORD", name: "Chicago O'Hare", country: "USA", lat: 41.98, lon: -87.9, hub: true },
  { iata: "DTW", name: "Detroit", country: "USA", lat: 42.21, lon: -83.35 },
  { iata: "MSP", name: "Minneapolis", country: "USA", lat: 44.88, lon: -93.22 },
  { iata: "STL", name: "St. Louis", country: "USA", lat: 38.75, lon: -90.37 },
  { iata: "MCI", name: "Kansas City", country: "USA", lat: 39.3, lon: -94.71 },
  { iata: "CMH", name: "Columbus", country: "USA", lat: 39.99, lon: -82.89 },
  { iata: "CLE", name: "Cleveland", country: "USA", lat: 41.41, lon: -81.85 },
  { iata: "PIT", name: "Pittsburgh", country: "USA", lat: 40.49, lon: -80.23 },
  { iata: "CVG", name: "Cincinnati", country: "USA", lat: 39.05, lon: -84.67 },
  { iata: "IND", name: "Indianapolis", country: "USA", lat: 39.72, lon: -86.29 },
  { iata: "MEM", name: "Memphis", country: "USA", lat: 35.04, lon: -89.98 },
  { iata: "HNL", name: "Honolulu", country: "USA", lat: 21.32, lon: -157.92 },
  { iata: "OGG", name: "Maui", country: "USA", lat: 20.9, lon: -156.43 },
  { iata: "ANC", name: "Anchorage", country: "USA", lat: 61.17, lon: -150.0 },
  { iata: "YYZ", name: "Toronto", country: "Canada", lat: 43.68, lon: -79.63, hub: true },
  { iata: "YUL", name: "Montréal", country: "Canada", lat: 45.47, lon: -73.74 },
  { iata: "YVR", name: "Vancouver", country: "Canada", lat: 49.19, lon: -123.18 },
  { iata: "YYC", name: "Calgary", country: "Canada", lat: 51.11, lon: -114.02 },
  { iata: "YEG", name: "Edmonton", country: "Canada", lat: 53.31, lon: -113.58 },
  { iata: "YOW", name: "Ottawa", country: "Canada", lat: 45.32, lon: -75.67 },
  { iata: "YHZ", name: "Halifax", country: "Canada", lat: 44.88, lon: -63.51 },
  { iata: "YWG", name: "Winnipeg", country: "Canada", lat: 49.91, lon: -97.24 },
  { iata: "MEX", name: "Mexico City", country: "Mexico", lat: 19.44, lon: -99.07 },
  { iata: "CUN", name: "Cancún", country: "Mexico", lat: 21.04, lon: -86.87 },
  { iata: "GDL", name: "Guadalajara", country: "Mexico", lat: 20.52, lon: -103.31 },
  { iata: "MTY", name: "Monterrey", country: "Mexico", lat: 25.78, lon: -100.11 },
  { iata: "SJD", name: "Los Cabos", country: "Mexico", lat: 23.15, lon: -109.72 },
  { iata: "PVR", name: "Puerto Vallarta", country: "Mexico", lat: 20.68, lon: -105.25 },
  { iata: "GUA", name: "Guatemala City", country: "Guatemala", lat: 14.58, lon: -90.53 },
  { iata: "SJO", name: "San José (Costa Rica)", country: "Costa Rica", lat: 9.99, lon: -84.21 },
  { iata: "PTY", name: "Panama City", country: "Panama", lat: 9.07, lon: -79.38 },
  { iata: "SAL", name: "San Salvador", country: "El Salvador", lat: 13.44, lon: -89.06 },
  { iata: "SJU", name: "San Juan", country: "Puerto Rico", lat: 18.44, lon: -66.0 },
  { iata: "PUJ", name: "Punta Cana", country: "Dominican Republic", lat: 18.57, lon: -68.36 },
  { iata: "SDQ", name: "Santo Domingo", country: "Dominican Republic", lat: 18.43, lon: -69.67 },
  { iata: "KIN", name: "Kingston", country: "Jamaica", lat: 17.94, lon: -76.79 },
  { iata: "MBJ", name: "Montego Bay", country: "Jamaica", lat: 18.5, lon: -77.91 },
  { iata: "NAS", name: "Nassau", country: "Bahamas", lat: 25.04, lon: -77.47 },
  { iata: "BGI", name: "Barbados", country: "Barbados", lat: 13.07, lon: -59.49 },
  { iata: "GRU", name: "São Paulo", country: "Brazil", lat: -23.43, lon: -46.47 },
  { iata: "GIG", name: "Rio de Janeiro", country: "Brazil", lat: -22.81, lon: -43.25 },
  { iata: "BSB", name: "Brasília", country: "Brazil", lat: -15.87, lon: -47.92 },
  { iata: "SSA", name: "Salvador", country: "Brazil", lat: -12.91, lon: -38.33 },
  { iata: "FOR", name: "Fortaleza", country: "Brazil", lat: -3.78, lon: -38.53 },
  { iata: "REC", name: "Recife", country: "Brazil", lat: -8.13, lon: -34.92 },
  { iata: "POA", name: "Porto Alegre", country: "Brazil", lat: -29.99, lon: -51.17 },
  { iata: "EZE", name: "Buenos Aires", country: "Argentina", lat: -34.82, lon: -58.54 },
  { iata: "SCL", name: "Santiago", country: "Chile", lat: -33.39, lon: -70.79 },
  { iata: "LIM", name: "Lima", country: "Peru", lat: -12.02, lon: -77.11 },
  { iata: "CUZ", name: "Cusco", country: "Peru", lat: -13.54, lon: -71.94 },
  { iata: "BOG", name: "Bogotá", country: "Colombia", lat: 4.7, lon: -74.15 },
  { iata: "MDE", name: "Medellín", country: "Colombia", lat: 6.17, lon: -75.43 },
  { iata: "CTG", name: "Cartagena", country: "Colombia", lat: 10.44, lon: -75.51 },
  { iata: "UIO", name: "Quito", country: "Ecuador", lat: -0.14, lon: -78.49 },
  { iata: "GYE", name: "Guayaquil", country: "Ecuador", lat: -2.16, lon: -79.88 },
  { iata: "MVD", name: "Montevideo", country: "Uruguay", lat: -34.84, lon: -56.03 },
  { iata: "ASU", name: "Asunción", country: "Paraguay", lat: -25.24, lon: -57.52 },
  { iata: "LPB", name: "La Paz", country: "Bolivia", lat: -16.51, lon: -68.19 },
  { iata: "SYD", name: "Sydney", country: "Australia", lat: -33.94, lon: 151.18, hub: true },
  { iata: "MEL", name: "Melbourne", country: "Australia", lat: -37.67, lon: 144.84 },
  { iata: "BNE", name: "Brisbane", country: "Australia", lat: -27.38, lon: 153.12 },
  { iata: "PER", name: "Perth", country: "Australia", lat: -31.94, lon: 115.97 },
  { iata: "ADL", name: "Adelaide", country: "Australia", lat: -34.95, lon: 138.53 },
  { iata: "CNS", name: "Cairns", country: "Australia", lat: -16.89, lon: 145.76 },
  { iata: "OOL", name: "Gold Coast", country: "Australia", lat: -28.16, lon: 153.5 },
  { iata: "AKL", name: "Auckland", country: "New Zealand", lat: -37.01, lon: 174.79 },
  { iata: "WLG", name: "Wellington", country: "New Zealand", lat: -41.33, lon: 174.81 },
  { iata: "CHC", name: "Christchurch", country: "New Zealand", lat: -43.49, lon: 172.53 },
  { iata: "ZQN", name: "Queenstown", country: "New Zealand", lat: -45.02, lon: 168.74 },
  { iata: "NAN", name: "Nadi (Fiji)", country: "Fiji", lat: -17.76, lon: 177.44 },
  { iata: "PPT", name: "Tahiti (Papeete)", country: "French Polynesia", lat: -17.56, lon: -149.61 },
];
